.\pullRequestInsightsTask\: &workingDirectory
trigger:
- master
stages:  
- stage: Build
  jobs:
  - job: Build
    pool:
      name: Hosted VS2017
      demands:
      - msbuild
    steps:
    - powershell: 
        npm install
      workingDirectory: *workingDirectory
      displayName: 'npm install'
    - powershell: 
        Rename-Item -Path ".\pullRequestInsightsTask\task.preProd" -NewName "task.json"
      displayName: 'specify task.json'
    - powershell: 
        tsc
      workingDirectory: .\pullRequestInsightsTask\
      displayName: 'compile'
    - powershell:
        npm test
      workingDirectory: *workingDirectory
      displayName: 'test'  
    - task: PRInsights@0
      displayName: Pull Request Insights
    - task: TfxInstaller@1
      inputs:
        version: 'v0.6.x'
    - powershell:
        Remove-Item './node_modules/fileset/test/fixtures/an (odd) filename.js' â€“recurse 
      workingDirectory: *workingDirectory
      displayName: 'Remove Bad Node File'
    - task: PackageVSTSExtension@1
      inputs:
        rootFolder: "./"
        patternManifest: "vss-extension-pp.json"
        outputPath: "./epsteam.PullRequestInsightsExtension.vsix"
      displayName: Package Task
    - task: PublishExtension@1
      inputs:
        connectTo: "VsTeam"
        connectedServiceName: "Visual Studio Marketplace"
        fileType: "vsix"
        vsixFile: "./epsteam.PullRequestInsightsExtension.vsix"
        rootFolder: "./"
        patternManifest: "vss-extension-pp.json"
      displayName: Publish Task
  
      
          
